logfile: "/var/log/exporter"
loglevel: "warn"
## Control logging in more detail
logging:
  cmd: warn
  repository: info
  measurement: debug
  exporter: info
  exporter/kih/dgws: warn

version: "1.0_build1"
environment: "dev"

export:
  start: 2019-06-01 # must be a date
  retrydays: 15
  backend: "kih"
  oioxds:
    xdsgenerator:
      url: http://kih-xds-generator:9020/api/createphmr
      healthcheck: http://kih-xds-generator:9020/actuator/health

proxy:
  port: 8360
  scheme: "http"
  host: "localhost"

app:
  url: "http://localhost:8360"
  port: 8360

clinician:
  batchsize: 50
  url: "https://oth-demo.oth.io/clinician/api"

authentication:
  key: ""
  secret: ""

database:
  hostname: "devdb"
  username: "opentele"
  password: "opentele"
  type: "mysql"
  port: 3306
  database: "exporter"
