name: Pull Request CI

on:
  pull_request: ~

jobs:
  pr_build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: ~1.19

# Cache GO stuff
    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
                
# Checkout source code
    - uses: actions/checkout@v3

    - name: Build
      run: ./ci-build/build.sh

    - name: Integration test
      run: ./ci-build/integration-test.sh